language: python
python:
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# command to run tests
script:
  - pytest --cov=app --cov-fail-under=100

after_success:
  - codecov
